---
name: 🚀 Feature Request 
description: Suggest an idea for this project
title: "🚀 [REQUEST]: "
labels: ["feature-request"]
assignees: []
projects: ["Team-Sync"]

body:
  - type: textarea
    id: description
    attributes:
      label: "Describe"
      description: A brief and clear description of the features you are proposing.
    validations:
      required: true

  - type: textarea
    id: how-to
    attributes:
      label: "How to Implement Features"
      description: Describe how to implement the function.
    validations:
      required: false

  - type: textarea
    id: checklist
    attributes:
      label: "✅ 체크리스트"
      description: 만들고자 하는 feature에 대해서 체크리스트를 제공해주세요!
      value: |
        - [ ] 
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: "Additional Explanation"
      description: Fill out additional parts or reference links that you need to know.
    validations:
      required: false
